export default function init(){
    localStorage.setItem("touristToken", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjYzU1MmJjZGQyNWE3MDlkOWQ5ODAxNSIsImlhdCI6MTU1NjQzNTY0NCwiZXhwIjoxNTU2NTIyMDQ0fQ.48UYdDxf0m5Rl7jsEtBsIR-X9dYlMUMZRMnFsp70VUs");
    localStorage.setItem("managerToken", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjYzU0NTAzMmI0Y2RmMDc4MDUyZWE1MyIsImlhdCI6MTU1NjQzMjEzMSwiZXhwIjoxNTU2NTE4NTMxfQ.XOfAFTjKquZbgoh7ndsB-RztpJr7V8qHVRN7l0k1IQg");
};